quas/core/products/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from core.products.views import FindRobotView, RobotCompareView, get_datasheet, get_datasheets, ProductDetailView, HomeView
app_name = 'core'

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("quas.ico")),
         ),
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>/', ProductDetailView.as_view(), name='product'),
    path('brand/<slug>', HomeView.as_view(), name='brand'),
    path('findrobot/', FindRobotView.as_view(), name='findrobot'),
    path('robotcompare/', RobotCompareView.as_view(), name='robotcompare'),
    path('get_datasheet/', get_datasheet, name='get_datasheet'),
    path('get_datasheets/', get_datasheets, name='get_datasheets'),
]

quas/core/robot/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from core.robot.views import FindRobotView, RobotCompareView, get_datasheet, get_datasheets, ItemDetailView, HomeView
app_name = 'core'

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("quas.ico")),
         ),
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('brand/<slug>', HomeView.as_view(), name='brand'),
    path('findrobot/', FindRobotView.as_view(), name='findrobot'),
    path('robotcompare/', RobotCompareView.as_view(), name='robotcompare'),
    path('get_datasheet/', get_datasheet, name='get_datasheet'),
    path('get_datasheets/', get_datasheets, name='get_datasheets'),

]

quas/quas/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include( 'core.products.urls')),
    path('user/', include( 'core.users.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

quas/core/products/models.py
from django.db import models
from core.models import BaseModel
from django.shortcuts import reverse
from core.products.utils import global_parameters
from core.calculators import Calculators
from core.products.utils.global_parameters import (
    LABEL_CHOICES, PRODUCT_TYPES, DATA_TYPES, IMAGE_TYPES)
from core.utils.error_management import ErrorService


class Application(BaseModel):

    def __str__(self):
        return self.name


class AttributeGroup(BaseModel):

    def __str__(self):
        return self.name


class AttributeConf(BaseModel):
    description = models.CharField(max_length=500, blank=True,
                                   null=True)
    is_direct_proportion = models.BooleanField()
    coefficient_mapping = models.JSONField(default=dict, null=True, blank=True)
    attribute_groups = models.ManyToManyField('AttributeGroup')
    product_type = models.CharField(choices=PRODUCT_TYPES, max_length=250,
                                    blank=True, null=True)
    data_type = models.CharField(choices=DATA_TYPES, max_length=50)

    def __str__(self):
        return self.name


class Attribute(BaseModel):
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE)
    value = models.JSONField(default=dict)
    conf = models.ForeignKey('products.AttributeConf', on_delete=models.CASCADE)
    value_calculator = models.CharField(choices=Calculators.get_calculators(),
                                        max_length=250, blank=True, null=True)
    calculated_value = models.DecimalField(max_digits=9, decimal_places=2,
                                           null=True, blank=True)

    def get_value(self):
        if self.value_calculator:
            return getattr(Calculators,
                           self.value_calculator)(**self.value).result

        if self.conf.data_type not in ['dict', 'list']:
            return self.value.get('default_value')
        return [self.value, ""]

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.calculated_value = self.get_value()[0]
        super(Attribute, self).save(
            force_insert=force_insert, force_update=force_update, using=using,
            update_fields=update_fields)

    def __str__(self):
        return "{} - {}".format(self.product.name, self.name)


# Add customer rating table, image table
class Product(BaseModel):
    main_slug = models.CharField(max_length=200)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)

    product_type = models.CharField(choices=PRODUCT_TYPES, max_length=10)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slogan = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField()

    price = models.DecimalField(max_digits=9, decimal_places=2,
                                null=True, blank=True)

    performance_rating = models.IntegerField(null=True, blank=True)
    customer_rating = models.IntegerField(null=True, blank=True)

    @property
    def is_hidden(self):
        return self.extra_fields.get("is_hidden") or False

    def save(self, *args, **kwargs):
        try:
            self.customer_rating = self.calculate_customer_rating()
            self.performance_rating = self.calculate_performance_rating()
        except:
            print("ERROR")
        finally:
            super(Product, self).save()

    def get_brand_url(self):
        return reverse("core:brand", kwargs={
            'slug': self.brand
        })

    def get_sales_url(self):
        return

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_attributes_by_attribute_group(self, attribute_group):
        # duzelt
        return Attribute.objects.filter(product_id=self.pk,
                                        conf__attrubte_groups=attribute_group)

    def calculate_performance_rating(self):
        return getattr(Calculators, 'general_performance_calculator')(
            product=self).result

    def calculate_customer_rating(self):
        return 86

    def custom_calculation(self, *args, **kwargs):
        return

    def get_datasheet(self):
        return self.attribute_set.all()

    def get_variants(self):
        return Product.objects.filter(main_slug=self.main_slug).exclude(pk=self.pk)

    def __str__(self):
        return self.name


class Brand(BaseModel):
    """
    Brand info, name, country, date, point, etc...
    """
    # country =
    year_of_foundation = models.DateField()

    def __str__(self):
        return self.name


class ProductImage(BaseModel):
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='robots/images')
    type = models.CharField(choices=IMAGE_TYPES, max_length=250)
    is_active = models.BooleanField()

    def __str__(self):
        return "{} - {}_{}".format(self.product.name, self.type, self.slug)

quas/core/robot/models.py
from django.db import models
from django.shortcuts import reverse
from core.robot.utils import global_parameters
from multiselectfield import MultiSelectField

CATEGORY_CHOICES = global_parameters.CATEGORY_CHOICES

LABEL_CHOICES = global_parameters.LABEL_CHOICES

ROBOT_APPLICATIONS = global_parameters.ROBOT_APPLICATIONS

AXIS_MOVEMENT = global_parameters.AXIS_MOVEMENT

MOUNTING = global_parameters.MOUNTING

DATASHEET = global_parameters.DATASHEET


class Axis(models.Model):
    name = models.CharField(default="Axis Info", max_length=50)
    axis1_speed = models.IntegerField(default=1)  # degree/s
    axis1_movement = models.CharField(choices=AXIS_MOVEMENT, max_length=50)

    axis2_speed = models.IntegerField(default=1)  # degree/s
    axis2_movement = models.CharField(choices=AXIS_MOVEMENT, max_length=50)

    axis3_speed = models.IntegerField(default=1)  # degree/s
    axis3_movement = models.CharField(choices=AXIS_MOVEMENT, max_length=50)

    axis4_speed = models.IntegerField(default=1)  # degree/s
    axis4_movement = models.CharField(choices=AXIS_MOVEMENT, max_length=50)

    axis5_speed = models.IntegerField(default=1)  # degree/s
    axis5_movement = models.CharField(choices=AXIS_MOVEMENT, max_length=50)

    axis6_speed = models.IntegerField(default=1)  # degree/s
    axis6_movement = models.CharField(choices=AXIS_MOVEMENT, max_length=50)

    def __str__(self):
        return self.name


class Robot(models.Model):
    # -------------------GENERAL INFOS---------------------------
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=4)
    # application = models.CharField(choices=ROBOT_APPLICATIONS, max_length=4)
    application = MultiSelectField(choices=ROBOT_APPLICATIONS, max_length=250, blank=True, null=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    description = models.TextField()
    slug = models.SlugField()
    image = models.ImageField()
    slogan = models.CharField(max_length=100, null=True, blank=True)
    # --------------------RATINGS--------------------------
    performance_rating = models.IntegerField(default=1)
    customer_rating = models.IntegerField(default=1)
    # speed = models.IntegerField(default =1)
    # power = models.IntegerField(default =1)
    # accuracy = models.IntegerField(default =1)

    # -------------------FINANCIAL INFOS-------------------------
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    # ----------------------DATASHEET----------------------------
    working_range_image = models.ImageField(upload_to='robots/working_range_images/')

    number_of_axes = models.IntegerField(default=6)
    payload = models.IntegerField(default=1)  # kg
    reach = models.FloatField(default=1)  # metre
    repeatability = models.FloatField(default=1)  # mm
    picking_cycle = models.FloatField(default=1)  # sec 300x25x25 with 1kg payload
    mounting = MultiSelectField(choices=MOUNTING, max_length=30)
    weight = models.IntegerField(default=1)  # kg

    controller = models.ForeignKey('Controller', on_delete=models.CASCADE)

    axis = models.OneToOneField(Axis, null=True, blank=True,
                                on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    def get_brand_url(self):
        return reverse("core:brand", kwargs={
            'slug': self.brand
        })

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    def get_datasheet(self):
        datasheet = {}
        for attribute_group, attributes in global_parameters.ATTRIBUTE_GROUPS.items():
            datasheet[attribute_group] = {}
            for attribute in attributes:
                if attribute == "axis":
                    for i in range(1, self.number_of_axes+1):
                        datasheet[attribute_group].update({
                            "Axis"+str(i): "Speed : " + str(getattr(self.axis, "axis"+str(i)+"_speed") )+ \
                                   "  Movement : " + getattr(self.axis, "axis"+str(i)+"_movement")
                        })
                else:
                    datasheet[attribute_group].update({
                        attribute.replace("_", " ").title() : getattr(self, attribute)
                    })
        datasheet.pop("Information")
        return datasheet


class Brand(models.Model):
    title = models.CharField(max_length=100)
    '''
    Brand infos, name, country, date, point, etc...
    '''

    def __str__(self):
        return self.title


class Controller(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    # ----------------DATASHEET------------------

    def __str__(self):
        return self.title


class RobotClass(models.Model):
    title = models.CharField(max_length=50)
    attributes = models.JSONField()
    attributes_kwargs = models.JSONField()

    def __str__(self):
        return self.title

quas/core/products/views.py
import random
import string
import json

from django.shortcuts import render
from django.views.generic import ListView, DetailView, View

from rest_framework.views import APIView
from rest_framework import viewsets
from core.products.models import Product, Attribute
from core.products.serializers import ProductSerializer, AttributeSerializer

from core.products.utils import findrobot_query as frq


class ProductView(viewsets.ModelViewSet):
    queryset = Product.objects.prefetch_related('productimage_set',
                                                'attribute_set')
    serializer_class = ProductSerializer


class AttributeView(viewsets.ModelViewSet):
    queryset = Attribute.objects.select_related('conf')
    serializer_class = AttributeSerializer


def get_datasheet(request, *args, **kwargs):
    robot = request.GET.get("products")
    context = {
        "products": Product.objects.get(slug=robot)
    }
    return render(request, "partials/datasheet-table-single.html", context)


def get_datasheets(request, *args, **kwargs):
    robot_1 = request.GET.get("robot_1")
    robot_2 = request.GET.get("robot_2")
    context = {
        "robot_1": Product.objects.get(slug=robot_1),
        "robot_2": Product.objects.get(slug=robot_2),
    }
    return render(request, "partials/datasheet-table-double.html", context)


class RobotCompareView(APIView):
    def get(self, *args, **kwargs):
        return render(self.request, "products-compare.html")

    def post(self, *args, **kwargs):
        pass


class FindRobotView(View):
    def get(self, *args, **kwargs):
        if not self.request.GET.get('query') == "true":
            return render(self.request, "findrobot.html")
        else:
            data = json.loads(self.request.GET.get("parameters"))
            return frq.FindRobot(self.request, data).__get__()


def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


def products(request):
    context = {
        'items': Product.objects.all()
    }
    return render(request, "products.html", context)


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid


class HomeView(ListView):
    model = Product
    paginate_by = 10
    template_name = "home.html"


class ProductDetailView(DetailView):
    model = Product
    template_name = "products.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_hidden is False:
            context = self.get_context_data(object=self.object)
            return self.render_to_response(context)
        return render(request, "404.html", "")

quas/core/robot/views.py
import random
import string
import json
import stripe
from django.conf import settings
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View

from core.robot.models import Robot

from core.robot.utils import findrobot_query as frq


def get_datasheet(request, *args, **kwargs):
    robot = request.GET.get("robot")
    context = {
        "robot": Robot.objects.get(slug=robot)
    }
    return render(request, "partials/datasheet-table-single.html", context)


def get_datasheets(request, *args, **kwargs):
    robot_1 = request.GET.get("robot_1")
    robot_2 = request.GET.get("robot_2")
    context = {
        "robot_1": Robot.objects.get(slug=robot_1),
        "robot_2": Robot.objects.get(slug=robot_2),
    }
    return render(request, "partials/datasheet-table-double.html", context)


class RobotCompareView(View):
    def get(self, *args, **kwargs):
        return render(self.request, "robot-compare.html")

    def post(self, *args, **kwargs):
        pass


class FindRobotView(View):
    def get(self, *args, **kwargs):
        if not self.request.GET.get('query') == "true":
            return render(self.request, "findrobot.html")
        else:
            data = json.loads(self.request.GET.get("parameters"))
            return frq.FindRobot(self.request, data).__get__()

    def post(self, *args, **kwargs):
        return HttpResponse(self.request, "POST", status=200)


stripe.api_key = settings.STRIPE_SECRET_KEY


def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


def products(request):
    context = {
        'items': Robot.objects.all()
    }
    return render(request, "products.html", context)


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid


class HomeView(ListView):
    model = Robot
    paginate_by = 10
    template_name = "home.html"


class ItemDetailView(DetailView):
    model = Robot
    template_name = "robot.html"

quas/templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>
    <div class="mt-3 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

quas/templates/deneme.html
<!--<!DOCTYPE html>-->

<html>
<meta charset="utf-8">
<head>
    {% load static %}
<script src="{% static 'script.js' %}"></script>

<title>SELAM</title>
</head>
<body onload="run()">
<div align="center">
<h1> ArgeMarkt yakında sizlerle!</h1>
<h2> O gelene kadar zaman geçirelim!</h2>
</div>
    <div align="center">
    <canvas id="canvas" width="700" height="220" style="border:1px solid #d3d3d3;">
anaa</canvas>

</div>
<div align="center">
    <p>SKOR </p>
    <p id="score">0</p>
</div>
</body>
</html>

quas/templates/findrobot.html
{% extends "base.html" %}
{% load humanize %}
{% load cart_template_tags %}
{% block content %}
{% load static %}
<main>
    <script type="text/javascript">
        navbar_active("FindRobot_button");
    </script>
<!-- SEARCH SCREEN -->
<div class="container">
<!-- SEARCH SCREEN -->
<div class="card mt-4 mb-4 ">

    <h5 class="card-header info-color white-text text-center py-4 unique-color" >
        <strong>For This Application</strong>
    </h5>

    <!--Card content-->
    <div class="card-body px-lg-5 mt-4">

        <form id="findrobot_form" class="text-center" style="color: #757575;" method="POST">
            {% csrf_token %}
            <div id="findrobot_form_div"></div>
            <!-- Sign in button -->
        </form>
        <script src="{% static 'js/jquery-3.4.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/modules/robot-module-tools.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/modules/dynamic-forms.js' %}" type="text/javascript"></script>
        <script>
            field_selector();
        </script>
        <!-- Form -->

{% if query == True %}
<h1 align="center">Best Robot is One of these:</h1>
<!-- SEARCH RESULTS -->
    <!-- FOR LOOP -->
    <!-- Card -->
</div>
<div class="container">
<section class="text-center mt-4 mb-4">

<div class="row wow fadeIn">
    {% if robots|length < 1 %}
    <div class="col" align="center"><h5 align="center">Unfortunately, couldn't find a matching robot...</h5></div>
    {% endif %}
    {% for robot in robots %}
    <div class="col-lg-3 col-md-6 mb-4 animated fadeInLeft">
        <div class="card">
            <div class="row">
                <div class="col-lg-1 mr-2"><span class="badge green"><h4>{{robot.performance_rating}}</h4></span></div>
                <div class="col">
                <!-- Card image -->
                <img class="card-img-top" src="{{robot.image.url}}" alt="Card image cap">
                </div>
            </div>
          <!-- Card content -->
            <div class="card-body" style="border-top-width: 2px;border-top-style: solid;">

            <!-- Title -->
                <h5>
                  <strong>
                    <a href="{{ robot.get_absolute_url }}" class="dark-grey-text"><span style="color:darkblue;">{{robot.brand}}</span> {{ robot.title }}
                      <span class="badge badge-pill {{ robot.get_label_display }}-color">Best Match!</span>
                    </a>
                  </strong>
                </h5>
            <!-- Text -->
            <p class="card-text">Şimdilik Dursun</p>
            <!-- Button -->
            <a href="#" class="btn btn-primary">Details</a>

            </div>
        </div>

    </div>
       {% endfor %}
</section>
</div>
{% endif %}
<!-- Card -->
<!-- SEARCH RESULTS -->
</main>

{% endblock content %}

quas/templates/product.html
{% extends "base.html" %}
{% load humanize %}
{% load cart_template_tags %}
{% block content %}
{% load static %}
<!-- DEFINE COLORS BY RATINGS -->



  <main class="mt-5 pt-4">
    <div id = "main_container" class="container dark-grey-text mt-5">

      <div class="row wow fadeIn">
        <!-- Left (Brand + title) -->
        <div class="col-md-6 mb-4">
          <a href = "{{ object.get_brand_url }}">
            <h1 align="center"> {{ object.brand }} </h1>
          </a>
          <span> <h1 align="center">{{ object.title }} </h1></span>
          </div>
        <!-- Right (Ratings) -->
        <div class="col-md-6 mb-4">
          <div class="col-md-6 mb-4" >
            <script>
          {% if object.performance_rating > 85 %}
             {% setvar "#32951d" as p_color %}
          {% elif object.performance_rating > 70 %}
            {% setvar "#68dd4f" as p_color %}
          {% elif object.performance_rating > 50 %}
            {% setvar "#dbc511" as p_color %}
          {% else %}
            {% setvar "darkred" as p_color %}
          {% endif %}
          </script>
            <div>
              <span class="badge blue mr-1" style = "margin-bottom:0.25em;font-size: 100%;">Performance Rating: </span>
              <span style="font-size: 150%;align:center;color:{{p_color}};">&nbsp; &nbsp; &nbsp; <b> {{ object.performance_rating }}</b> </span>
              </div>


        <div class="progress md-progress">
          <script>
          {% if object.customer_rating > 85 %}
             {% setvar "#32951d" as c_color %}
          {% elif object.customer_rating > 70 %}
            {% setvar "#68dd4f" as c_color %}
          {% elif object.customer_rating > 50 %}
            {% setvar "#dbc511" as c_color %}
          {% else %}
            {% setvar "darkred" as c_color %}
          {% endif %}
        </script>
            <div class="progress-bar" role="progressbar" style="background-color: {{p_color}}; width: {{ object.performance_rating }}%"
                 aria-valuenow="{{ object.performance_rating }}" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        </div>

          <div class="col-md-6 mb-4">
          <span class="badge blue mr-1" style = "font-size: 100%;margin-bottom:0.25em">Customer Rating &nbsp; &nbsp; : </span>
            <span style="font-size: 150%;align:center;color:{{c_color}};">&nbsp; &nbsp; &nbsp; &nbsp;<b>{{ object.customer_rating }}</b></span>
        <div class="progress md-progress">

            <div class="progress-bar" role="progressbar" style="background-color: {{c_color}}; width: {{ object.customer_rating }}%"
                 aria-valuenow="{{ object.performance_rating }}" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        </div>
        </div>
        </div>


    <!-- PRODUCT INFO -->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4 text-center">

          <img src="{{ object.image.url }}" class="animated fadeInLeft" alt="">

        </div>
        <!--Grid column img-fluid-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price|intcomma }}</del>
              </span>
              <span>${{ object.discount_price|intcomma }}</span>
              {% else %}
              <span>${{ object.price |intcomma }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> 
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>
          {% endcomment %}
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>{{object.description}}</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="{{ item.image.url }}" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="{{ item.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="{{ item.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}" type="text/javascript"></script>
    <script>
        $.ajax({
            type: "GET",
            url: "/get_datasheet",
            //data: {'csrfmiddlewaretoken': csrftoken},
            data: { "function": "get_datasheet",
                    "robot":"{{object.slug}}"
                    },
            success : function(data) {
            console.log(data);
                $("#main_container").append(data);
            }
        })
    </script>
  </main>

{% endblock content %}

quas/templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}